# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x0bsupplychain\"1\n\x0cStockRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x14\n\x0cwarehouse_id\x18\x02 \x01(\t\"@\n\x0fLowStockRequest\x12\x14\n\x0cwarehouse_id\x18\x01 \x01(\t\x12\x17\n\x0fthreshold_units\x18\x02 \x01(\x05\"k\n\rStockResponse\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x14\n\x0cwarehouse_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x15\n\rreorder_point\x18\x04 \x01(\x05\x12\x0e\n\x06status\x18\x05 \x01(\t2\xa6\x01\n\x10InventoryService\x12\x46\n\rGetStockLevel\x12\x19.supplychain.StockRequest\x1a\x1a.supplychain.StockResponse\x12J\n\x0cListLowStock\x12\x1c.supplychain.LowStockRequest\x1a\x1a.supplychain.StockResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKREQUEST']._serialized_start=32
  _globals['_STOCKREQUEST']._serialized_end=81
  _globals['_LOWSTOCKREQUEST']._serialized_start=83
  _globals['_LOWSTOCKREQUEST']._serialized_end=147
  _globals['_STOCKRESPONSE']._serialized_start=149
  _globals['_STOCKRESPONSE']._serialized_end=256
  _globals['_INVENTORYSERVICE']._serialized_start=259
  _globals['_INVENTORYSERVICE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
